FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../core ./core
COPY main.py .
COPY .env* ./

EXPOSE 8000

CMD ["python", "main.py"]
